// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: RPG.GameServer/Protos/character.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace RPG.GameServer.Protos {
  public static partial class CharacterService
  {
    static readonly string __ServiceName = "rpg.CharacterService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::RPG.GameServer.Protos.CharacterRequest> __Marshaller_rpg_CharacterRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RPG.GameServer.Protos.CharacterRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::RPG.GameServer.Protos.CharacterIdReply> __Marshaller_rpg_CharacterIdReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RPG.GameServer.Protos.CharacterIdReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::RPG.GameServer.Protos.CharacterIdRequest> __Marshaller_rpg_CharacterIdRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RPG.GameServer.Protos.CharacterIdRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::RPG.GameServer.Protos.CharacterReply> __Marshaller_rpg_CharacterReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RPG.GameServer.Protos.CharacterReply.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::RPG.GameServer.Protos.CharacterRequest, global::RPG.GameServer.Protos.CharacterIdReply> __Method_CreateCharacter = new grpc::Method<global::RPG.GameServer.Protos.CharacterRequest, global::RPG.GameServer.Protos.CharacterIdReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateCharacter",
        __Marshaller_rpg_CharacterRequest,
        __Marshaller_rpg_CharacterIdReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::RPG.GameServer.Protos.CharacterIdRequest, global::RPG.GameServer.Protos.CharacterReply> __Method_GetCharacter = new grpc::Method<global::RPG.GameServer.Protos.CharacterIdRequest, global::RPG.GameServer.Protos.CharacterReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetCharacter",
        __Marshaller_rpg_CharacterIdRequest,
        __Marshaller_rpg_CharacterReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::RPG.GameServer.Protos.CharacterRequest, global::RPG.GameServer.Protos.CharacterIdReply> __Method_UpdateCharacter = new grpc::Method<global::RPG.GameServer.Protos.CharacterRequest, global::RPG.GameServer.Protos.CharacterIdReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateCharacter",
        __Marshaller_rpg_CharacterRequest,
        __Marshaller_rpg_CharacterIdReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::RPG.GameServer.Protos.CharacterIdRequest, global::RPG.GameServer.Protos.CharacterIdReply> __Method_DeleteCharacter = new grpc::Method<global::RPG.GameServer.Protos.CharacterIdRequest, global::RPG.GameServer.Protos.CharacterIdReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteCharacter",
        __Marshaller_rpg_CharacterIdRequest,
        __Marshaller_rpg_CharacterIdReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::RPG.GameServer.Protos.CharacterReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of CharacterService</summary>
    [grpc::BindServiceMethod(typeof(CharacterService), "BindService")]
    public abstract partial class CharacterServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::RPG.GameServer.Protos.CharacterIdReply> CreateCharacter(global::RPG.GameServer.Protos.CharacterRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::RPG.GameServer.Protos.CharacterReply> GetCharacter(global::RPG.GameServer.Protos.CharacterIdRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::RPG.GameServer.Protos.CharacterIdReply> UpdateCharacter(global::RPG.GameServer.Protos.CharacterRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::RPG.GameServer.Protos.CharacterIdReply> DeleteCharacter(global::RPG.GameServer.Protos.CharacterIdRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for CharacterService</summary>
    public partial class CharacterServiceClient : grpc::ClientBase<CharacterServiceClient>
    {
      /// <summary>Creates a new client for CharacterService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public CharacterServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for CharacterService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public CharacterServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected CharacterServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected CharacterServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::RPG.GameServer.Protos.CharacterIdReply CreateCharacter(global::RPG.GameServer.Protos.CharacterRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateCharacter(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::RPG.GameServer.Protos.CharacterIdReply CreateCharacter(global::RPG.GameServer.Protos.CharacterRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateCharacter, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::RPG.GameServer.Protos.CharacterIdReply> CreateCharacterAsync(global::RPG.GameServer.Protos.CharacterRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateCharacterAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::RPG.GameServer.Protos.CharacterIdReply> CreateCharacterAsync(global::RPG.GameServer.Protos.CharacterRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateCharacter, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::RPG.GameServer.Protos.CharacterReply GetCharacter(global::RPG.GameServer.Protos.CharacterIdRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCharacter(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::RPG.GameServer.Protos.CharacterReply GetCharacter(global::RPG.GameServer.Protos.CharacterIdRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetCharacter, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::RPG.GameServer.Protos.CharacterReply> GetCharacterAsync(global::RPG.GameServer.Protos.CharacterIdRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCharacterAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::RPG.GameServer.Protos.CharacterReply> GetCharacterAsync(global::RPG.GameServer.Protos.CharacterIdRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetCharacter, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::RPG.GameServer.Protos.CharacterIdReply UpdateCharacter(global::RPG.GameServer.Protos.CharacterRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateCharacter(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::RPG.GameServer.Protos.CharacterIdReply UpdateCharacter(global::RPG.GameServer.Protos.CharacterRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateCharacter, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::RPG.GameServer.Protos.CharacterIdReply> UpdateCharacterAsync(global::RPG.GameServer.Protos.CharacterRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateCharacterAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::RPG.GameServer.Protos.CharacterIdReply> UpdateCharacterAsync(global::RPG.GameServer.Protos.CharacterRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateCharacter, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::RPG.GameServer.Protos.CharacterIdReply DeleteCharacter(global::RPG.GameServer.Protos.CharacterIdRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteCharacter(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::RPG.GameServer.Protos.CharacterIdReply DeleteCharacter(global::RPG.GameServer.Protos.CharacterIdRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteCharacter, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::RPG.GameServer.Protos.CharacterIdReply> DeleteCharacterAsync(global::RPG.GameServer.Protos.CharacterIdRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteCharacterAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::RPG.GameServer.Protos.CharacterIdReply> DeleteCharacterAsync(global::RPG.GameServer.Protos.CharacterIdRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteCharacter, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override CharacterServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new CharacterServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(CharacterServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CreateCharacter, serviceImpl.CreateCharacter)
          .AddMethod(__Method_GetCharacter, serviceImpl.GetCharacter)
          .AddMethod(__Method_UpdateCharacter, serviceImpl.UpdateCharacter)
          .AddMethod(__Method_DeleteCharacter, serviceImpl.DeleteCharacter).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, CharacterServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CreateCharacter, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::RPG.GameServer.Protos.CharacterRequest, global::RPG.GameServer.Protos.CharacterIdReply>(serviceImpl.CreateCharacter));
      serviceBinder.AddMethod(__Method_GetCharacter, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::RPG.GameServer.Protos.CharacterIdRequest, global::RPG.GameServer.Protos.CharacterReply>(serviceImpl.GetCharacter));
      serviceBinder.AddMethod(__Method_UpdateCharacter, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::RPG.GameServer.Protos.CharacterRequest, global::RPG.GameServer.Protos.CharacterIdReply>(serviceImpl.UpdateCharacter));
      serviceBinder.AddMethod(__Method_DeleteCharacter, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::RPG.GameServer.Protos.CharacterIdRequest, global::RPG.GameServer.Protos.CharacterIdReply>(serviceImpl.DeleteCharacter));
    }

  }
}
#endregion
