<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Domain\ValueObjects\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MongoDB.Driver" Version="2.19.0" />
      <PackageReference Include="MongoDB.Driver.Core" Version="2.30.0" />
      <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
      <PackageReference Include="Serilog" Version="4.3.1-dev-02387" />
      <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
      <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.1-dev-02307" />
      <PackageReference Include="Serilog.Sinks.Console" Version="6.0.1-dev-00953" />
    </ItemGroup>

</Project>
