<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RPG.Domain\RPG.Domain.csproj"/>
    <ProjectReference Include="..\RPG.Infrastructure\RPG.Infrastructure.csproj"/>
    <ProjectReference Include="..\RPG.AI\RPG.AI.csproj"/>
    <ProjectReference Include="..\RPG.Abstractions\RPG.Abstractions.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\MovementService\"/>
  </ItemGroup>

</Project>
