syntax = "proto3";

package rpg.query.v1;

option csharp_namespace = "RPG.GameServer.QueryProtos";

message Vector3 {
  float x = 1;
  float y = 2;
  float z = 3;
}

message RotationState {
  bool is_rotating = 1;
  float direction = 2;
}

message Location {
  string world_id = 1;
  string map_id = 2;
  Vector3 position = 3;
  RotationState rotation = 4;
}

message TagEntry {
  string key = 1;
  string value = 2;
}

message Component {
  string type = 1;
  string data_json = 2;
}

message ComponentEntry {
  string type = 1;
  string data_json = 2;
}

message InventorySlot {
  string item_id = 1;
  string item_name = 2;
  int32 quantity = 3;
  map<string,string> metadata = 4;
}
