syntax = "proto3";
option csharp_namespace = "RPG.GameServer.Protos";
package rpg;
import "character.proto";

service SessionService {
  rpc CreateSession (CreateSessionRequest) returns (SessionReply);
  rpc GetSession (SessionIdRequest) returns (SessionReply);
  rpc EndSession (EndSessionRequest) returns (SessionReply);
  rpc HeartbeatSession (SessionHeartbeatRequest) returns (SessionReply);
}

message Session {
  string id = 1;
  string characterId = 2;
  string playerId = 3;
  int64 startedAt = 4;
  Location lastKnownLocation = 5;
  bool active = 6;
  int64 lastActivityAt = 7;
  string status = 8;
}

message CreateSessionRequest {
  string characterId = 1;
  string playerId = 2;
}

message EndSessionRequest {
  string sessionId = 1;
}

message SessionIdRequest {
  string sessionId = 1;
}

message SessionHeartbeatRequest {
  string sessionId = 1;
  Location location = 2;
}

message SessionReply {
  Session session = 1;
}

