syntax = "proto3";
option csharp_namespace = "RPG.GameServer.QueryProtos";

package rpg.query;

service NpcQuery {
  rpc GetNpc(NpcGetByIdRequest) returns (NpcSingleReply);
  rpc ListNpcs(NpcListRequest) returns (NpcListReply);
  rpc GetNpcsByIds(NpcGetByIdsRequest) returns (NpcListReply);
}

message NpcSingleReply { Npc npc = 1; }
message NpcListReply { repeated Npc npcs = 1; }

message Npc {
  string id = 1;
  string name = 2;
  int32 level = 3;
  bool is_moving = 4;
  float x = 5;
  float y = 6;
  float z = 7;
  float rotation = 8;
  repeated string tags = 9;
}

message NpcGetByIdRequest { string id = 1; }
message NpcListRequest {}
message NpcGetByIdsRequest { repeated string ids = 1; }
