syntax = "proto3";
option csharp_namespace = "RPG.GameServer.QueryProtos";

package rpg.query;

service SkillQuery {
  rpc GetSkill(SkillGetByIdRequest) returns (SkillSingleReply);
  rpc ListSkills(SkillListRequest) returns (SkillListReply);
  rpc GetSkillsByIds(SkillGetByIdsRequest) returns (SkillListReply);
}

message SkillSingleReply { Skill skill = 1; }
message SkillListReply { repeated Skill skills = 1; }

message Skill {
  string id = 1;
  string name = 2;
  repeated string tags = 3;
}

message SkillGetByIdRequest { string id = 1; }
message SkillListRequest {}
message SkillGetByIdsRequest { repeated string ids = 1; }
